[package]
name = "jetline"
version = "0.1.0"
authors = ["Liwen Guo <lg@livven.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
colored = "1.9.3"
dirs = "2.0.2"
git2 = "0.13.0"
itertools = "0.9.0"
