name: ci

on:
  push:
    branches:
      - "**"

env:
  BIN_NAME: jetline

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
          override: true
      - name: Check formatting
        run: |
          npm ci
          npm run format-check
      - name: Run clippy
        run: |
          cargo clippy -- -D warnings
  build:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Build and test
        run: |
          cargo build --verbose --release
          cargo test --verbose --release
      - name: Collect artifacts
        shell: bash
        run: |
          mkdir artifacts
          cp target/release/$BIN_NAME artifacts || cp target/release/$BIN_NAME.exe artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ env.BIN_NAME }}-${{ github.run_id }}-rust-${{ matrix.rust }}-${{ matrix.os }}
          path: artifacts
